project:
  type: website
  output-dir: docs

website:
  title: "A Young Man's Mathematical Journey"
  
  # NEW: Add a top navigation bar
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: feed.qmd
        text: Feed / Blog
      - href: about.qmd
        text: About Me

  # EXISTING: Your topic sidebar
  sidebar:
    style: "docked"
    search: true
    contents:
      - section: "Topology"
        contents:
          - htpy-theory/mosher-tangora-prblm1.qmd

      - section: "Representation Theory"
        contents:
          - rep-theory/rep-theory/the-basics.qmd
          - rep-theory/rep-theory/schurs-lemma.qmd
      - section: "Field Theory"

     
format:
  html:
    theme: cosmo
    toc: true
    html-math-method: mathjax
    include-in-title: math-macros.html
    include-in-header: math-macros.html




